target("base")
    set_kind("$(kind)")
    set_targetdir("$(libdir)")

    -- add_deps("base")
    -- add_packages("spdlog")

    add_includedirs("include", {public = true})
    add_headerfiles("include/(**.hpp)", "include/(**.h)")
    -- add_headerfiles("src/(**.hpp)", {install = false})
    add_files("src/**.cpp")

    set_configdir("include/test/base")
    add_configfiles("config.h.in", {public = true})

    on_load(function (target) 
        import("lua.auto", {rootdir = os.projectdir()})
        auto().target_autoname(target)
        auto().library_autodefine(target)
    end)
    after_build(function (target) 
        import("lua.auto", {rootdir = os.projectdir()})
        auto().target_autoclean(target)
    end)
target_end()